### ISSUE TITLE
could you update your paper link

### ISSUE THREAD

**Issue by ForrestPi** [GitBoSun/ARAPReg#1]
Amazing! but I cannot find your paper, could you update your paper link
Thanks

**Comment by GitBoSun** [comment]
Hi, thanks for your interest in our work! I haven't uploaded it to arxiv yet. You can  check it on  google drive: https://drive.google.com/file/d/13yazDUk0Cyqsqnus-sNoXEiRoXbTOpwp/view?usp=sharing.
