### ISSUE TITLE
Questions about the implementation

### ISSUE THREAD

**Issue by daidedou** [GitBoSun/ARAPReg#3]
Hi, 

In the paper it is said that you apply alternating minimization in order to optimize both $z_i$ and $\theta$ alternatively in the auto decoder setting:

"
Our implementation applies one epoch of optimizing θ for each alternating optimization iteration.
When the network parameters θ are fixed, ...., our implementation applies one epoch of optimizing zi for each alternating iteration. The total number of alternating iterations is set as 30 in this paper.
"

I can't find anything like this in the code. It seems that you changed the alternating optimization to a common optimization with $z_i$ defined as embeddings of the training data (trained with different learning rates). Am I understanding it correctly? Is there any reason for doing this -- besides, from my guess, an easier open source implementation :)? Does it change the network performance? And does the pretrained checkpoint use this implementation?

Anyway, thank you very much to share this code!

**Comment by xiangruhuang** [comment]
Hi,

Thank you for your interest in our work.

For the ease of implementation, the current version does not use alternating minimization. 

The released code (as well as the checkpoint) should reproduce the results in the paper.  The pretrained checkpoint also use this implementation.

**Comment by daidedou** [comment]
Thanks you very much for the answer, it is clearer for me!
